import test from'node:test';import assert from'node:assert/strict';import{COLLECTION_LIMITS,EXERCISE_PHASES,addObservation,advanceExercise,closeExercise,closeoutReadiness,createExercise,createInject,decideCommunication,decideProposal,enterCloseoutReview,exerciseScore,exportAfterAction,forecastExercise,forecastStateFingerprint,forecastStatus,openRisks,resolveInject,resumeResponse,stageCommunication,stageProposal,updateObjective}from'../src/engine.js';
test('advancing time applies active inject pressure deterministically',()=>{const exercise=createExercise('outage');const before={...exercise.metrics};const result=advanceExercise(exercise,30);assert.equal(result.exercise.clock,45);assert.ok(result.exercise.metrics.impact>before.impact);assert.ok(result.exercise.metrics.service<before.service);});
test('agent response remains staged until a human decision function approves it',()=>{const exercise=createExercise('outage');const staged=stageProposal(exercise,{title:'Route to backup processor',category:'continuity',rationale:'Reduce dependency on the failing payment path.',objective_id:'contain',resource_id:'sre',resource_units:2,effects:{impact:-10,uncertainty:-5,fatigue:2,trust:1,service:12}});assert.equal(staged.proposal.status,'staged');assert.equal(staged.exercise.decisions.length,0);const approved=decideProposal(staged.exercise,staged.proposal.id,'approved','Human approved');assert.equal(approved.exercise.decisions.length,1);assert.equal(approved.exercise.resources.find((item)=>item.id==='sre').allocated,2);assert.ok(approved.exercise.metrics.service>exercise.metrics.service);});
test('facilitator inject creation uses bounded effects and stable ids',()=>{const exercise=createExercise('festival');const result=createInject(exercise,{title:'Water delivery delayed',description:'A supplier vehicle is held outside the event perimeter.',category:'vendor',severity:4,delay_minutes:10,deadline_minutes:40,effects:{impact:99,uncertainty:3,fatigue:2,trust:-2,service:-6}});assert.equal(result.inject.id,'inject-1');assert.equal(result.inject.effects.impact,20);assert.equal(result.inject.createdAt,25);});
test('forecast is reproducible for a fixed seed',()=>{const exercise=createExercise('ransomware');const first=forecastExercise(exercise,{horizonMinutes:90,simulations:500,seed:77});const second=forecastExercise(exercise,{horizonMinutes:90,simulations:500,seed:77});assert.deepEqual(first,second);assert.ok(first.containmentProbability>=0&&first.containmentProbability<=100);});
test('open risk view includes injects, objectives, and staged items',()=>{let exercise=createExercise('outage');exercise=stageProposal(exercise,{title:'Freeze retries',category:'containment',rationale:'Stop retry amplification while the failure domain is isolated.',effects:{impact:-6,uncertainty:-3,fatigue:0,trust:0,service:2}}).exercise;const risks=openRisks(exercise);assert.ok(risks.activeInjects.length>=1);assert.ok(risks.openObjectives.length>=1);assert.equal(risks.stagedResponses.length,1);});
test('after-action export contains only human-approved decisions as decisions',()=>{const exercise=createExercise('outage');const markdown=exportAfterAction(exercise,[]);assert.match(markdown,/Human-approved decisions/);assert.match(markdown,/None recorded/);assert.match(markdown,/Training simulation only/);assert.ok(exerciseScore(exercise)>=0);});

test('exercise scores are informative rather than clamped at 100',()=>{const scores=['outage','ransomware','festival'].map((preset)=>exerciseScore(createExercise(preset)));assert.ok(scores.every((score)=>score>0&&score<100));assert.ok(new Set(scores).size>1);});

test('delayed injects use an activation-relative deadline and partial exposure',()=>{const exercise=createExercise('festival');const created=createInject(exercise,{title:'Late supplier',description:'A fictional delivery arrives after the planned response window.',category:'vendor',severity:4,delay_minutes:20,deadline_minutes:40,effects:{impact:10}});assert.equal(created.inject.createdAt,35);assert.equal(created.inject.deadline,75);const advanced=advanceExercise(created.exercise,30);assert.ok(advanced.exercise.metrics.impact>exercise.metrics.impact);const fullExposure=createInject(exercise,{title:'Immediate supplier',description:'A fictional delivery fails at the start of the response window.',category:'vendor',severity:4,delay_minutes:0,deadline_minutes:40,effects:{impact:10}});assert.ok(advanceExercise(fullExposure.exercise,30).exercise.metrics.impact>advanced.exercise.metrics.impact);});

test('an inject activating at the interval endpoint has zero pressure and does not erase recovery',()=>{const clear=createExercise('outage');clear.injects=[];const baseline=advanceExercise(clear,60).exercise;const scheduled=createInject(clear,{title:'Endpoint signal',description:'A fictional zero-effect inject activates exactly at the horizon.',category:'vendor',severity:1,delay_minutes:60,deadline_minutes:30,effects:{}}).exercise;const advanced=advanceExercise(scheduled,60).exercise;assert.equal(advanced.metrics.impact,baseline.metrics.impact);assert.equal(advanced.metrics.service,baseline.metrics.service);});

test('clock advancement is inject-order invariant and stable across step sizes',()=>{const exercise=createExercise('outage');exercise.metrics.impact=96;exercise.injects=[{id:'inject-b',title:'Positive pressure',description:'Fictional pressure.',category:'technical',severity:5,createdAt:0,deadline:300,status:'active',effects:{impact:20}},{id:'inject-a',title:'Counter pressure',description:'Fictional counter-pressure.',category:'technical',severity:5,createdAt:0,deadline:300,status:'active',effects:{impact:-20}}];const forward=advanceExercise(exercise,240).exercise;const reversedInput=structuredClone(exercise);reversedInput.injects.reverse();const reversed=advanceExercise(reversedInput,240).exercise;assert.deepEqual(forward.metrics,reversed.metrics);let stepped=structuredClone(exercise);for(let index=0;index<16;index+=1)stepped=advanceExercise(stepped,15).exercise;assert.deepEqual(forward.metrics,stepped.metrics);assert.equal(forward.clock,stepped.clock);});

test('forecast includes scheduled inject effects and shares the clock engine baseline',()=>{const exercise=createExercise('outage');const quiet=createInject(exercise,{title:'Scheduled signal',description:'A scheduled fictional development with no direct metric effects.',category:'vendor',severity:2,delay_minutes:30,deadline_minutes:40,effects:{}}).exercise;const pressured=createInject(exercise,{title:'Scheduled signal',description:'A scheduled fictional development with material direct effects.',category:'vendor',severity:2,delay_minutes:30,deadline_minutes:40,effects:{impact:18,service:-18,uncertainty:12}}).exercise;const quietForecast=forecastExercise(quiet,{horizonMinutes:60,simulations:1000,seed:55});const pressureForecast=forecastExercise(pressured,{horizonMinutes:60,simulations:1000,seed:55});assert.ok(pressureForecast.ranges.impact.median>quietForecast.ranges.impact.median);assert.ok(pressureForecast.ranges.service.median<quietForecast.ranges.service.median);const baseline=advanceExercise(pressured,60).exercise;assert.ok(Math.abs(pressureForecast.ranges.impact.median-baseline.metrics.impact)<2);});

test('forecast run keys fingerprint state as well as inputs',()=>{const exercise=createExercise('outage');const staged=stageProposal(exercise,{title:'Contain retries',category:'containment',rationale:'Reduce retry amplification on the simulated payment path.',effects:{impact:-8,service:6}});const approved=decideProposal(staged.exercise,staged.proposal.id,'approved');assert.notEqual(forecastStateFingerprint(exercise),forecastStateFingerprint(approved.exercise));assert.notEqual(forecastExercise(exercise).runKey,forecastExercise(approved.exercise).runKey);});

test('closeout is a guarded human-owned lifecycle transition',()=>{let exercise=createExercise('outage');assert.equal(closeoutReadiness(exercise).ready,false);exercise.closeout.rationale='The learning goals are complete and unresolved injects are documented.';exercise.closeout.lessons=['Review resource conflicts before approval.'];const staged=stageCommunication(exercise,{audience:'customers',purpose:'Status',message:'This is a factual simulated status update for review.'});assert.match(closeoutReadiness(staged.exercise).blockers.join(' '),/staged communication/);const reviewed=decideCommunication(staged.exercise,staged.communication.id,'rejected').exercise;const entered=enterCloseoutReview(reviewed).exercise;assert.equal(entered.phase,EXERCISE_PHASES.CLOSEOUT_REVIEW);assert.throws(()=>advanceExercise(entered,15),/Return to the response phase/);const resumed=resumeResponse(entered).exercise;assert.equal(resumed.phase,EXERCISE_PHASES.RESPONSE);const reentered=enterCloseoutReview(resumed).exercise;const closed=closeExercise(reentered,'2026-08-30T00:00:00.000Z').exercise;assert.equal(closed.phase,EXERCISE_PHASES.CLOSED);assert.equal(closed.status,'closed');assert.throws(()=>resumeResponse(closed),/cannot be reopened/);});

test('inject resolution rejects future and repeated outcomes',()=>{const exercise=createExercise('outage');const created=createInject(exercise,{title:'Future vendor issue',description:'A fictional vendor issue scheduled for later in the exercise.',category:'vendor',severity:2,delay_minutes:20,deadline_minutes:30,effects:{impact:2}});assert.throws(()=>resolveInject(created.exercise,created.inject.id,'Resolved early'),/future inject/);const active=advanceExercise(created.exercise,20).exercise;const resolved=resolveInject(active,created.inject.id,'Resolved after activation').exercise;assert.throws(()=>resolveInject(resolved,created.inject.id,'Resolved twice'),/already been resolved/);});

test('open risks expose scheduled injects and AAR exports observations',()=>{let exercise=createExercise('festival');exercise=createInject(exercise,{title:'Scheduled transport issue',description:'A fictional transport interruption activates later.',category:'operations',severity:3,delay_minutes:20,deadline_minutes:35,effects:{service:-4}}).exercise;exercise.observations.push({id:'observation-test',text:'Queue growth was visible before escalation.',tags:['timing'],at:exercise.clock});const risks=openRisks(exercise);assert.equal(risks.scheduledInjects.length,1);const markdown=exportAfterAction(exercise,[]);assert.match(markdown,/Training observations/);assert.match(markdown,/Queue growth was visible/);});

test('completed objectives preserve consistent progress and require explicit reopening',()=>{let exercise=createExercise('outage');exercise=updateObjective(exercise,'contain',80,'complete','Completed in exercise').exercise;assert.equal(exercise.objectives.find((item)=>item.id==='contain').progress,100);assert.throws(()=>updateObjective(exercise,'contain',-40,null,'Unexpected regression'),/Explicitly set status/);const reopened=updateObjective(exercise,'contain',-40,'blocked','Evidence changed').exercise;const objective=reopened.objectives.find((item)=>item.id==='contain');assert.equal(objective.progress,60);assert.equal(objective.status,'blocked');});

test('forecast freshness exposes generation fingerprints and becomes stale after relevant board changes',()=>{const exercise=createExercise('outage');const forecast=forecastExercise(exercise,{horizonMinutes:60,simulations:200,seed:91});const current=forecastStatus(exercise,forecast);assert.equal(current.stale,false);assert.equal(current.generatedAtClock,exercise.clock);assert.equal(current.generatedAtStateFingerprint,forecast.stateFingerprint);assert.equal(current.currentStateFingerprint,forecast.stateFingerprint);const advanced=advanceExercise(exercise,15).exercise;const stale=forecastStatus(advanced,forecast);assert.equal(stale.stale,true);assert.notEqual(stale.currentStateFingerprint,stale.generatedAtStateFingerprint);});

test('after-action Markdown neutralizes user-controlled chapter and HTML injection',()=>{const exercise=createExercise('outage');const forged='Visible text\n\n## Forged chapter\n<script>alert(1)</script>';exercise.title=forged;exercise.objectives[0].title=forged;exercise.objectives[0].owner=forged;exercise.injects[0].title=forged;exercise.injects[0].outcome=forged;exercise.decisions.push({id:'decision-malicious',proposalId:'proposal-malicious',title:forged,note:forged,at:exercise.clock});exercise.communications.push({id:'comms-malicious',audience:forged,purpose:'Status',message:forged,status:'approved',reviewedAt:exercise.clock});exercise.observations.push({id:'observation-malicious',text:forged,tags:[forged],at:exercise.clock});exercise.closeout.rationale=forged;exercise.closeout.lessons=[forged];const markdown=exportAfterAction(exercise,[{time:forged,actor:forged,label:forged}]);assert.equal(markdown.match(/^## /gm)?.length,9);assert.equal(markdown.match(/^## Human-approved decisions$/gm)?.length,1);assert.doesNotMatch(markdown,/^## Forged chapter$/m);assert.doesNotMatch(markdown,/<script>/);});

test('critical exercise collections reject growth at their explicit limits',()=>{const injects=createExercise('outage');injects.injects=Array.from({length:COLLECTION_LIMITS.injects},(_,index)=>({id:`inject-cap-${index}`}));assert.throws(()=>createInject(injects,{title:'Beyond cap',description:'A fictional inject that should be rejected at capacity.',category:'vendor',severity:2,effects:{}}),/Inject limit reached/);const proposals=createExercise('outage');proposals.proposals=Array.from({length:COLLECTION_LIMITS.proposals},(_,index)=>({id:`proposal-cap-${index}`}));assert.throws(()=>stageProposal(proposals,{title:'Beyond cap',category:'continuity',rationale:'This staged response should be rejected at capacity.',effects:{}}),/Response proposal limit reached/);const communications=createExercise('outage');communications.communications=Array.from({length:COLLECTION_LIMITS.communications},(_,index)=>({id:`comms-cap-${index}`}));assert.throws(()=>stageCommunication(communications,{audience:'customers',purpose:'Beyond cap',message:'This communication should be rejected at capacity.'}),/Communication limit reached/);const observations=createExercise('outage');observations.observations=Array.from({length:COLLECTION_LIMITS.observations},(_,index)=>({id:`observation-cap-${index}`}));assert.throws(()=>addObservation(observations,{observation:'This observation should be rejected at capacity.'}),/Observation limit reached/);const decisionBase=stageProposal(createExercise('outage'),{title:'Capacity decision',category:'continuity',rationale:'This response reaches the human decision collection guard.',effects:{}}).exercise;decisionBase.decisions=Array.from({length:COLLECTION_LIMITS.decisions},(_,index)=>({id:`decision-cap-${index}`}));assert.throws(()=>decideProposal(decisionBase,decisionBase.proposals[0].id,'approved'),/Approved decision limit reached/);});

test('closeout readiness is rechecked after entering review',()=>{const exercise=createExercise('outage');exercise.closeout.rationale='The learning goals are complete and unresolved items are documented.';exercise.closeout.lessons=['Keep the visible review boundary explicit.'];const reviewed=enterCloseoutReview(exercise).exercise;reviewed.closeout.rationale='';assert.equal(closeoutReadiness(reviewed).ready,false);assert.throws(()=>closeExercise(reviewed),/Add a closeout rationale/);});
