import test from'node:test';import assert from'node:assert/strict';import{createWebMCPRegistry,validateSchema}from'../src/webmcp.js';const schema={type:'object',properties:{title:{type:'string',minLength:3,maxLength:20},severity:{type:'integer',minimum:1,maximum:5},effects:{type:'object',properties:{impact:{type:'number',minimum:-20,maximum:20}},additionalProperties:false}},required:['title','severity','effects'],additionalProperties:false};test('schema validator accepts a valid inject payload',()=>assert.deepEqual(validateSchema(schema,{title:'New inject',severity:4,effects:{impact:8}}),[]));test('schema validator rejects missing and unknown fields',()=>{const errors=validateSchema(schema,{title:'x',extra:true});assert.ok(errors.some((error)=>error.includes('required')));assert.ok(errors.some((error)=>error.includes('not allowed')));});test('schema validator enforces nested numeric bounds',()=>{const errors=validateSchema(schema,{title:'Valid title',severity:8,effects:{impact:30}});assert.equal(errors.length,2);});

const definition=(overrides={})=>({name:'test_tool',title:'Test tool',description:'Validate a narrow payload.',inputSchema:{type:'object',properties:{count:{type:'integer',minimum:1,maximum:5}},required:['count'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input)=>({message:'Validated count.',count:input.count}),...overrides});

test('registry retries when native WebMCP appears after preview mode',async()=>{let context=null;const registrations=[];const registry=createWebMCPRegistry({contextProvider:()=>context,bridgeTarget:{}});await registry.sync([definition()]);assert.equal(registry.status().mode,'preview');context={registerTool:async(tool,options)=>registrations.push({tool,options})};await registry.sync([definition()]);assert.equal(registry.status().mode,'native');assert.equal(registrations.length,1);assert.equal(registry.status().registeredToolCount,1);});

test('registry retries the same metadata after a registration failure',async()=>{let shouldFail=true;let calls=0;const context={registerTool:async()=>{calls+=1;if(shouldFail)throw new Error('temporary failure');}};const registry=createWebMCPRegistry({contextProvider:()=>context,bridgeTarget:{}});await registry.sync([definition()]);assert.equal(registry.status().mode,'preview');assert.match(registry.status().lastError,/temporary failure/);shouldFail=false;await registry.sync([definition()]);assert.equal(registry.status().mode,'native');assert.equal(calls,2);});

test('metadata changes abort old registrations and re-register dynamic schemas',async()=>{const registrations=[];const context={registerTool:async(tool,{signal})=>registrations.push({tool,signal})};const registry=createWebMCPRegistry({contextProvider:()=>context,bridgeTarget:{}});await registry.sync([definition()]);await registry.sync([definition()]);assert.equal(registrations.length,1);await registry.sync([definition({inputSchema:{type:'object',properties:{id:{type:'string',enum:['new-id']}},required:['id'],additionalProperties:false}})]);assert.equal(registrations.length,2);assert.equal(registrations[0].signal.aborted,true);assert.equal(registrations[1].signal.aborted,false);});

test('native execute wrapper validates schema, honors cancellation, and returns one plain object',async()=>{let registered;const context={registerTool:async(tool)=>{registered=tool;}};const registry=createWebMCPRegistry({contextProvider:()=>context,bridgeTarget:{}});await registry.sync([definition()]);await assert.rejects(()=>registered.execute({count:8},{signal:new AbortController().signal}),/at most 5/);await assert.rejects(()=>registered.execute({count:2,extra:true},{signal:new AbortController().signal}),/not allowed/);const controller=new AbortController();controller.abort();await assert.rejects(()=>registered.execute({count:2},{signal:controller.signal}),{name:'AbortError'});const result=await registered.execute({count:2},{signal:new AbortController().signal});assert.deepEqual(result,{message:'Validated count.',count:2});assert.equal('content'in result,false);assert.equal('structuredContent'in result,false);});

test('native and Tool Lab execution reject wrapped or over-budget results',async()=>{const registry=createWebMCPRegistry({contextProvider:()=>null,bridgeTarget:{}});await registry.sync([definition({execute:async()=>({content:[],structuredContent:{count:2}})})]);await assert.rejects(()=>registry.executeTool('test_tool',{count:2}),/plain object/);await registry.sync([definition({execute:async()=>({message:'x'.repeat(2000)})})]);await assert.rejects(()=>registry.executeTool('test_tool',{count:2}),/1500-character budget/);});
