import { PRESETS } from './data.js';
import { COLLECTION_LIMITS, EXERCISE_PHASES, activeInjects, addObservation, advanceExercise, closeExercise, closeoutReadiness, createExercise, createInject, decideCommunication, decideProposal, enterCloseoutReview, exerciseScore, exportAfterAction, forecastExercise, forecastStatus, formatClock, metricTone, openRisks, resolveInject, resumeResponse, stageCommunication, stageProposal, updateObjective } from './engine.js';
import { segmentJson, segmentText } from './paging.js';
import { StatePersistenceError, commitState } from './state.js';
import { createWebMCPRegistry } from './webmcp.js';

const STORAGE_KEY = 'drillboard.exercise.v2';
const MAX_HISTORY = 36;
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const elements = {
  preset: $('#preset-select'), role: $('#role-select'), reset: $('#reset-exercise'), advance15: $('#advance-15'), advance30: $('#advance-30'), undo: $('#undo-change'),
  clock: $('#exercise-clock'), scenarioTitle: $('#scenario-title'), scenarioSubtitle: $('#scenario-subtitle'), status: $('#exercise-status'), score: $('#exercise-score'),
  impact: $('#metric-impact'), uncertainty: $('#metric-uncertainty'), fatigue: $('#metric-fatigue'), trust: $('#metric-trust'), service: $('#metric-service'),
  objectives: $('#objective-list'), injects: $('#inject-list'), resources: $('#resource-list'), proposals: $('#proposal-list'), communications: $('#communication-list'),
  forecast: $('#forecast-panel'), riskList: $('#risk-list'), activity: $('#activity-list'), webmcpStatus: $('#webmcp-status'), webmcpError: $('#webmcp-error'), toolButton: $('#tool-lab-button'),
  toolDialog: $('#tool-dialog'), toolSelect: $('#tool-select'), toolInput: $('#tool-input'), toolRun: $('#tool-run'), toolOutput: $('#tool-output'), toolClose: $('#close-tool-dialog'),
  forecastButton: $('#run-forecast'), exportButton: $('#export-aar'), closeoutRationale: $('#closeout-rationale'), closeoutLessons: $('#closeout-lessons'),
  closeoutCheck: $('#closeout-check'), closeoutReviewButton: $('#closeout-review-button'), resumeResponseButton: $('#resume-response-button'), closeoutButton: $('#closeout-button'), closeoutStatus: $('#closeout-status'), theme: $('#theme-toggle'), roleCopy: $('#role-copy'),
};

function nowLabel() { return new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date()); }
function initialState(preset='outage') { return { exercise:createExercise(preset), history:[], activity:[{time:nowLabel(),actor:'human',label:`Opened ${PRESETS[preset].name}`}], theme:'dark' }; }
function loadState(){ try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)); if(parsed?.exercise?.version===2) return {...parsed,history:Array.isArray(parsed.history)?parsed.history:[]};}catch{} return initialState(); }
let state=loadState();
const isResponseOpen=()=>state.exercise.status==='open'&&state.exercise.phase===EXERCISE_PHASES.RESPONSE;
function persist(nextState=state){ localStorage.setItem(STORAGE_KEY,JSON.stringify(nextState)); }
function snapshot(source=state){ return JSON.stringify({exercise:source.exercise,activity:source.activity}); }
function mutate(label,actor,operation,{history=true}={}){
  if(state.exercise.status==='closed') throw new Error('The exercise is closed and read-only. Reset it to start another drill.');
  if(state.exercise.phase!==EXERCISE_PHASES.RESPONSE) throw new Error('The exercise is in closeout review. A person must resume response before any mutation.');
  try{
    state=commitState(state,(draft)=>{
      if(history) draft.history=[...draft.history.slice(-(MAX_HISTORY-1)),{snapshot:snapshot(state),actor,label}];
      operation(draft);
      draft.activity=[{time:nowLabel(),actor,label},...draft.activity].slice(0,60);
    },persist);
  }catch(error){render();if(error instanceof StatePersistenceError)elements.roleCopy.textContent=error.message;throw error;}
  render();
}
function undo(){if(!isResponseOpen())throw new Error('Changes cannot be undone during closeout review or after closure.');const entry=state.history.at(-1);if(!entry)return;const restored=JSON.parse(typeof entry==='string'?entry:entry.snapshot);state=commitState(state,(draft)=>{draft.history.pop();const history=draft.history;Object.assign(draft,restored,{history});draft.activity=[{time:nowLabel(),actor:'human',label:`User undid the previous ${entry.actor||'simulation'} change`},...draft.activity].slice(0,60);},persist);render();}
function resetExercise(key=state.exercise.presetKey){const next=initialState(key);try{persist(next);}catch(error){throw new Error(`Could not reset the exercise; the current board was preserved. ${error instanceof Error?error.message:String(error)}`);}state=next;render();}
function replaceExercise(next,label,actor){ mutate(label,actor,(draft)=>{draft.exercise=next;draft.exercise.closeout.staged=false;}); }
function escapeHtml(value){return String(value).replace(/[&<>\"]/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'})[character]);}
function downloadText(filename,content){const blob=new Blob([content],{type:'text/markdown'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
function showInlineError(control,error){const container=control.closest('article,li')||control.parentElement;container.querySelector('.inline-error')?.remove();const message=document.createElement('p');message.className='inline-error';message.setAttribute('role','alert');message.textContent=error instanceof Error?error.message:String(error);container.append(message);}

function renderHeader(){
  const responseOpen=isResponseOpen();
  elements.preset.value=state.exercise.presetKey; elements.role.value=state.exercise.role; elements.clock.textContent=formatClock(state.exercise.clock);
  elements.scenarioTitle.textContent=state.exercise.title; elements.scenarioSubtitle.textContent=state.exercise.subtitle; elements.status.textContent=state.exercise.phase==='closeout-review'?'closeout review':state.exercise.status;
  elements.score.textContent=exerciseScore(state.exercise); elements.role.disabled=!responseOpen; elements.undo.disabled=!responseOpen||!state.history.length; elements.advance15.disabled=elements.advance30.disabled=!responseOpen;
  elements.forecastButton.disabled=!responseOpen;
  elements.roleCopy.textContent=state.exercise.role==='coach'
    ? `${responseOpen?'Coach mode':'Read-only lifecycle phase'}: ${responseOpen?'the WebMCP surface registers analysis and staging tools; facilitator-only mutation tools are absent.':'mutation tools are unregistered until the user resumes response.'}`
    : `${responseOpen?'Facilitator mode':'Read-only lifecycle phase'}: ${responseOpen?'the WebMCP surface includes inject, clock, and objective tools. Finalization remains in visible review controls.':'mutation tools are unregistered until the user resumes response.'}`;
}
function renderMetric(key,element){const value=Math.round(state.exercise.metrics[key]);element.querySelector('strong').textContent=value;element.querySelector('.meter-fill').style.width=`${value}%`;element.dataset.tone=metricTone(key,value);element.setAttribute('aria-valuenow',String(value));}
function renderMetrics(){for(const [key,element] of Object.entries({impact:elements.impact,uncertainty:elements.uncertainty,fatigue:elements.fatigue,trust:elements.trust,service:elements.service}))renderMetric(key,element);}
function renderObjectives(){elements.objectives.innerHTML=state.exercise.objectives.map((objective)=>`<li class="objective ${objective.status}"><div><span class="priority ${objective.priority}">${objective.priority}</span><strong>${escapeHtml(objective.title)}</strong><small>${escapeHtml(objective.owner)} · deadline T+${formatClock(objective.deadline)}</small></div><div class="progress-wrap"><span>${Math.round(objective.progress)}%</span><div class="progress"><i style="width:${objective.progress}%"></i></div></div>${objective.status!=='complete'&&isResponseOpen()?`<button class="mini-button" data-progress-objective="${objective.id}">+20%</button>`:''}</li>`).join('');
  $$('[data-progress-objective]').forEach((button)=>button.addEventListener('click',()=>{const result=updateObjective(state.exercise,button.dataset.progressObjective,20,null,'Human exercise update');replaceExercise(result.exercise,`Advanced objective: ${result.objective.title}`,'human');}));}
function renderInjects(){const sorted=[...state.exercise.injects].sort((a,b)=>b.createdAt-a.createdAt);elements.injects.innerHTML=sorted.map((inject)=>`<li class="inject ${inject.status} ${inject.createdAt>state.exercise.clock?'future':''}"><div class="inject-time">T+${formatClock(inject.createdAt)}</div><div><span class="category">${escapeHtml(inject.category)}</span><strong>${escapeHtml(inject.title)}</strong><p>${escapeHtml(inject.description)}</p><small>Severity ${inject.severity} · deadline T+${formatClock(inject.deadline)} · ${inject.status}</small>${inject.outcome?`<em>${escapeHtml(inject.outcome)}</em>`:''}</div>${inject.status==='active'&&inject.createdAt<=state.exercise.clock&&isResponseOpen()?`<button class="mini-button" data-resolve-inject="${inject.id}">Resolve</button>`:''}</li>`).join('');
  $$('[data-resolve-inject]').forEach((button)=>button.addEventListener('click',()=>{const outcome=prompt('Record the simulated outcome:','Contained through the approved response.');if(!outcome)return;const result=resolveInject(state.exercise,button.dataset.resolveInject,outcome);replaceExercise(result.exercise,`Resolved inject: ${result.inject.title}`,'human');}));}
function renderResources(){elements.resources.innerHTML=state.exercise.resources.map((resource)=>{const available=resource.total-resource.allocated;return `<li><div><strong>${escapeHtml(resource.name)}</strong><small>${available} available · ${resource.allocated} allocated</small></div><div class="resource-dots" aria-label="${resource.allocated} of ${resource.total} allocated">${Array.from({length:resource.total},(_,index)=>`<i class="${index<resource.allocated?'used':''}"></i>`).join('')}</div></li>`;}).join('');}
function renderProposals(){
  const proposals=[...state.exercise.proposals].reverse();
  elements.proposals.innerHTML=proposals.length?proposals.map((proposal)=>{
    const metricPreview=Object.entries(proposal.effects).filter(([,value])=>value).map(([key,value])=>{const before=Math.round(state.exercise.metrics[key]);const after=Math.round(Math.max(0,Math.min(100,before+value)));return `<li><span>${escapeHtml(key)}</span><strong>${before} → ${after}</strong><small>${value>0?'+':''}${value}</small></li>`;});
    const objective=proposal.targetObjectiveId?state.exercise.objectives.find((item)=>item.id===proposal.targetObjectiveId):null;
    if(objective){const after=Math.min(100,objective.progress+30+proposal.resourceUnits*8);metricPreview.push(`<li><span>objective · ${escapeHtml(objective.title)}</span><strong>${Math.round(objective.progress)}% → ${Math.round(after)}%</strong><small>on approval</small></li>`);}
    const resource=proposal.resourceId?state.exercise.resources.find((item)=>item.id===proposal.resourceId):null;
    const resourceConflict=Boolean(proposal.status==='staged'&&resource&&resource.total-resource.allocated<proposal.resourceUnits);
    if(resource){const available=resource.total-resource.allocated;metricPreview.push(`<li class="${resourceConflict?'conflict':''}"><span>resource · ${escapeHtml(resource.name)}</span><strong>${available} → ${Math.max(0,available-proposal.resourceUnits)} available</strong><small>${resourceConflict?'insufficient now':`allocate ${proposal.resourceUnits}`}</small></li>`);}
    return `<article class="proposal ${proposal.status} ${resourceConflict?'resource-conflict':''}"><div class="proposal-heading"><span class="category">${escapeHtml(proposal.category)}</span><strong>${escapeHtml(proposal.title)}</strong><span class="proposal-status">${proposal.status}</span></div><p>${escapeHtml(proposal.rationale)}</p>${proposal.status==='staged'?`<div class="approval-preview"><strong>Approval would apply</strong><ul>${metricPreview.join('')||'<li><span>No direct simulated effects</span></li>'}</ul></div>`:`<div class="effect-row">${Object.entries(proposal.effects).filter(([,value])=>value).map(([key,value])=>`<span>${key} ${value>0?'+':''}${value}</span>`).join('')||'<span>No direct metric effect</span>'}</div>`}${resourceConflict?'<p class="inline-error" role="alert">Resource availability changed. Reject this proposal or review another response first.</p>':''}${proposal.status==='staged'&&isResponseOpen()?`<div class="button-row"><button class="button ghost" data-reject-proposal="${proposal.id}">Reject</button><button class="button primary" data-approve-proposal="${proposal.id}" ${resourceConflict?'disabled':''}>${resourceConflict?'Insufficient resources':'Approve response'}</button></div>`:''}</article>`;
  }).join(''):'<p class="empty">WebMCP-staged responses will appear here for visible user review.</p>';
  $$('[data-approve-proposal]').forEach((button)=>button.addEventListener('click',()=>{try{const note=prompt('Optional decision note:','Approved for the simulation.');if(note===null)return;const result=decideProposal(state.exercise,button.dataset.approveProposal,'approved',note);replaceExercise(result.exercise,`User approved response: ${result.proposal.title}`,'human');}catch(error){showInlineError(button,error);}}));
  $$('[data-reject-proposal]').forEach((button)=>button.addEventListener('click',()=>{const result=decideProposal(state.exercise,button.dataset.rejectProposal,'rejected','Rejected during human review.');replaceExercise(result.exercise,`Human rejected response: ${result.proposal.title}`,'human');}));}
function renderCommunications(){const items=[...state.exercise.communications].reverse();elements.communications.innerHTML=items.length?items.map((item)=>`<li class="communication ${item.status}"><div><span class="category">${escapeHtml(item.audience)}</span><strong>${escapeHtml(item.purpose)}</strong><p>${escapeHtml(item.message)}</p></div>${item.status==='staged'&&isResponseOpen()?`<div class="button-row"><button class="mini-button" data-reject-comms="${item.id}">Reject</button><button class="mini-button approve" data-approve-comms="${item.id}">Approve</button></div>`:`<span>${item.status}</span>`}</li>`).join(''):'<li class="empty">No communication drafts are staged.</li>';
  $$('[data-approve-comms]').forEach((button)=>button.addEventListener('click',()=>{const result=decideCommunication(state.exercise,button.dataset.approveComms,'approved');replaceExercise(result.exercise,`Human approved communication to ${result.communication.audience}`,'human');}));
  $$('[data-reject-comms]').forEach((button)=>button.addEventListener('click',()=>{const result=decideCommunication(state.exercise,button.dataset.rejectComms,'rejected');replaceExercise(result.exercise,`Human rejected communication to ${result.communication.audience}`,'human');}));}
function renderForecast(){const forecast=state.exercise.forecasts.at(-1);if(!forecast){elements.forecast.innerHTML='<p class="empty">Run a seeded forecast to stress-test the current response posture.</p>';return;}const status=forecastStatus(state.exercise,forecast);const labels={impact:'Impact',uncertainty:'Uncertainty',fatigue:'Fatigue',trust:'Trust',service:'Service',score:'Score'};elements.forecast.innerHTML=`<div class="forecast-freshness ${status.stale?'stale':'current'}" role="status"><strong>${status.stale?'Outdated forecast — board changed':'Current board forecast'}</strong><span>Generated T+${formatClock(status.generatedAtClock)} · state ${escapeHtml(status.generatedAtStateFingerprint)} · current ${escapeHtml(status.currentStateFingerprint)}</span></div><div class="forecast-score"><strong>${forecast.containmentProbability}%</strong><span>${status.stale?'historical simulated containment rate':'simulated containment rate'} in ${forecast.horizonMinutes} minutes</span></div><div class="forecast-table-wrap"><table class="forecast-table"><caption>Seed ${forecast.seed} · ${forecast.simulations} paths · generated at board T+${formatClock(status.generatedAtClock)}</caption><thead><tr><th>Metric</th><th>P10</th><th>Median</th><th>P90</th></tr></thead><tbody>${Object.entries(forecast.ranges).map(([key,range])=>`<tr><th>${labels[key]||escapeHtml(key)}</th><td>${range.p10}</td><td>${range.median}</td><td>${range.p90}</td></tr>`).join('')}</tbody></table></div><div><h3>Risk drivers at generation time</h3><ul>${forecast.riskDrivers.length?forecast.riskDrivers.map((driver)=>`<li>${escapeHtml(driver)}</li>`).join(''):'<li>No dominant driver identified.</li>'}</ul></div>${status.stale?'<p class="forecast-warning">Run a new forecast before treating this simulation as current.</p>':''}<p class="forecast-note">${escapeHtml(forecast.assumptions?.at(-1)||'Training signal only—not a prediction.')}</p>`;}
function renderRisks(){const risks=openRisks(state.exercise);const items=[...risks.activeInjects.map((risk)=>({label:risk.title,meta:`active inject · severity ${risk.severity}`,overdue:risk.overdue})),...risks.scheduledInjects.map((risk)=>({label:risk.title,meta:`scheduled inject · activates T+${formatClock(risk.activatesAt)}`,overdue:false})),...risks.openObjectives.map((risk)=>({label:risk.title,meta:`objective · ${risk.progress}%`,overdue:risk.overdue})),...risks.stagedResponses.map((risk)=>({label:risk.title,meta:'awaiting human response review',overdue:false})),...risks.stagedCommunications.map((risk)=>({label:`${risk.audience}: ${risk.purpose}`,meta:'awaiting communication review',overdue:false}))];elements.riskList.innerHTML=items.length?items.map((item)=>`<li class="${item.overdue?'overdue':''}"><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(item.meta)}</small></li>`).join(''):'<li class="empty">No open risks.</li>';}
function renderActivity(){elements.activity.innerHTML=state.activity.map((item)=>`<li><span class="actor ${item.actor}">${item.actor}</span><span>${escapeHtml(item.label)}</span><time>${item.time}</time></li>`).join('');}
function renderCloseout(){
  const closed=state.exercise.status==='closed';const reviewing=state.exercise.phase===EXERCISE_PHASES.CLOSEOUT_REVIEW;const readiness=closeoutReadiness(state.exercise);
  elements.closeoutRationale.value=state.exercise.closeout.rationale||'';elements.closeoutLessons.value=(state.exercise.closeout.lessons||[]).join('\n');
  elements.closeoutCheck.checked=false;elements.closeoutCheck.disabled=closed||!reviewing||!readiness.ready;elements.closeoutRationale.disabled=closed;elements.closeoutLessons.disabled=closed;
  elements.closeoutReviewButton.hidden=reviewing||closed;elements.closeoutReviewButton.disabled=!readiness.ready;
  elements.resumeResponseButton.hidden=!reviewing||closed;elements.closeoutButton.hidden=!reviewing||closed;elements.closeoutButton.disabled=closed||!readiness.ready;
  if(closed)elements.closeoutStatus.textContent=`Exercise closed ${new Date(state.exercise.closeout.closedAt).toLocaleString()}. All mutation tools are unregistered.`;
  else if(reviewing&&!readiness.ready)elements.closeoutStatus.textContent=`Closeout review blocked: ${readiness.blockers.join(' ')} Repair the draft here or resume response; closing remains disabled.`;
  else if(reviewing)elements.closeoutStatus.textContent=`Closeout review is active. WebMCP tools are read-only. ${readiness.unresolvedInjects.length} unresolved inject(s) and ${readiness.openObjectives.length} open objective(s) will be preserved in the AAR.`;
  else if(!readiness.ready)elements.closeoutStatus.textContent=`Closeout gate blocked: ${readiness.blockers.join(' ')}`;
  else elements.closeoutStatus.textContent='Closeout draft is ready for visible user review.';
  elements.closeoutStatus.className=`closeout-status ${closed?'closed':reviewing||state.exercise.closeout.staged?'staged':''}`;
}
function renderToolLab(){const tools=registry.listTools();const current=elements.toolSelect.value;const status=registry.status();elements.toolSelect.innerHTML=tools.map((tool)=>`<option value="${tool.name}">${tool.name}</option>`).join('');if(tools.some((tool)=>tool.name===current))elements.toolSelect.value=current;elements.webmcpStatus.textContent=`${status.lastError?'Native registration error · Tool Lab active':status.mode==='native'?'Native WebMCP':'Tool Lab fallback'} · ${tools.length} tools`;elements.webmcpStatus.dataset.mode=status.lastError?'error':status.mode;elements.webmcpStatus.title=status.lastError?`Native registration failed: ${status.lastError}`:'';elements.webmcpError.hidden=!status.lastError;elements.webmcpError.textContent=status.lastError?`Native WebMCP registration failed: ${status.lastError} Tool Lab remains available for diagnosis.`:'';}
function render(){document.documentElement.dataset.theme=state.theme;elements.theme.textContent=state.theme==='dark'?'Light':'Dark';renderHeader();renderMetrics();renderObjectives();renderInjects();renderResources();renderProposals();renderCommunications();renderForecast();renderRisks();renderActivity();renderCloseout();syncTools();}

const registry=createWebMCPRegistry({bridgeName:'__drillboardWebMCP',onStatus:renderToolLab});
const objectSchema=(properties={},required=[])=>({type:'object',properties,required,additionalProperties:false});
const stringSchema=(description,options={})=>({type:'string',description,...options});
const numberSchema=(description,minimum,maximum)=>({type:'number',description,minimum,maximum});
function schemaExample(schema={}){if(schema.type==='object')return Object.fromEntries((schema.required||[]).map((key)=>[key,schemaExample(schema.properties?.[key])]));if(schema.type==='array')return Array.from({length:schema.minItems||0},()=>schemaExample(schema.items));if(schema.type==='string')return schema.enum?.[0]??'Example'.padEnd(schema.minLength||0,' value');if(schema.type==='integer'||schema.type==='number')return schema.minimum??1;if(schema.type==='boolean')return true;return null;}
const effectSchema={type:'object',description:'Simulated metric deltas. Negative impact/uncertainty/fatigue and positive trust/service are beneficial.',properties:{impact:numberSchema('Impact delta.',-20,20),uncertainty:numberSchema('Uncertainty delta.',-20,20),fatigue:numberSchema('Fatigue delta.',-20,20),trust:numberSchema('Trust delta.',-20,20),service:numberSchema('Service-health delta.',-20,20)},additionalProperties:false};
const readOnly={readOnlyHint:true,untrustedContentHint:true};
const mutation={readOnlyHint:false,untrustedContentHint:true};
const roomSections=['summary','objectives','resources','injects','review_queue','observations','forecast','closeout'];
const aarSections=['summary','full','metrics','objectives','injects','decisions','communications','observations','forecast','closeout','activity'];
const aarHeadings={metrics:'Final metrics',objectives:'Objectives',injects:'Injects',decisions:'Human-approved decisions',communications:'Approved communications',observations:'Training observations',forecast:'Latest deterministic forecast',closeout:'Closeout',activity:'Activity trail'};
function compactForecast(){
  const latestForecast=state.exercise.forecasts.at(-1);
  const latestForecastStatus=forecastStatus(state.exercise,latestForecast);
  return latestForecast?{runKey:latestForecast.runKey,containmentProbability:latestForecast.containmentProbability,horizonMinutes:latestForecast.horizonMinutes,generatedAtClock:latestForecastStatus.generatedAtClock,generatedAtStateFingerprint:latestForecastStatus.generatedAtStateFingerprint,currentStateFingerprint:latestForecastStatus.currentStateFingerprint,stale:latestForecastStatus.stale}:null;
}
function roomSection(section){
  const readiness=closeoutReadiness(state.exercise);
  if(section==='summary')return {scenario:{title:state.exercise.title,clock:state.exercise.clock,status:state.exercise.status,phase:state.exercise.phase,agentRole:state.exercise.role},score:exerciseScore(state.exercise),metrics:state.exercise.metrics,counts:{objectives:state.exercise.objectives.length,injects:state.exercise.injects.length,stagedResponses:state.exercise.proposals.filter((item)=>item.status==='staged').length,stagedCommunications:state.exercise.communications.filter((item)=>item.status==='staged').length,observations:state.exercise.observations.length},latestForecast:compactForecast(),closeout:{staged:state.exercise.closeout.staged,ready:readiness.ready,blockers:readiness.blockers},availableSections:roomSections,userControlBoundary:'WebMCP stages work; approval and finalization require explicit visible user confirmation.'};
  if(section==='objectives')return state.exercise.objectives;
  if(section==='resources')return state.exercise.resources.map((item)=>({...item,available:item.total-item.allocated}));
  if(section==='injects')return state.exercise.injects;
  if(section==='review_queue')return {responses:state.exercise.proposals,communications:state.exercise.communications};
  if(section==='observations')return state.exercise.observations;
  if(section==='forecast')return {latest:state.exercise.forecasts.at(-1)||null,freshness:forecastStatus(state.exercise,state.exercise.forecasts.at(-1))};
  return {closeout:state.exercise.closeout,readiness};
}
function roomSummary(section='summary',cursor=0){const data=roomSection(section);return section==='summary'?{message:'Compact current Drillboard room summary.',section,data}:{message:`Drillboard ${section} JSON segment. Continue with nextCursor until null.`,section,...segmentJson(data,cursor)};}
function riskPage(kind='all',cursor=0){const risks=openRisks(state.exercise);const data=kind==='all'?risks:kind==='injects'?{activeInjects:risks.activeInjects,scheduledInjects:risks.scheduledInjects}:kind==='objectives'?risks.openObjectives:kind==='responses'?risks.stagedResponses:risks.stagedCommunications;return {message:'Bounded open-risk JSON segment. Continue with nextCursor until null.',kind,...segmentJson(data,cursor)};}
function aarSectionMarkdown(section){const markdown=exportAfterAction(state.exercise,state.activity);if(section==='full')return markdown;const firstHeading=markdown.indexOf('\n## ');if(section==='summary')return `${markdown.slice(0,firstHeading)}\n\nAvailable sections: ${aarSections.join(', ')}`;const heading=`## ${aarHeadings[section]}`;const start=markdown.indexOf(heading);if(start<0)return `${heading}\n- Not available`;const next=markdown.indexOf('\n## ',start+heading.length);return markdown.slice(start,next<0?markdown.length:next).trimEnd();}
function aarPage(section='summary',cursor=0){return {message:'Bounded Markdown AAR segment. Continue with nextCursor until null.',section,format:'text/markdown',...segmentText(aarSectionMarkdown(section),cursor)};}
function setExerciseFromTool(next,label){mutate(label,'agent',(draft)=>{draft.exercise=next;draft.exercise.closeout.staged=false;});}
function requireFacilitatorTool(){if(state.exercise.role!=='facilitator'||!isResponseOpen())throw new Error('This tool is available only during response in human-selected Facilitator mode.');}
function definitions(){
  const objectiveIds=state.exercise.objectives.map((item)=>item.id);
  const resourceIds=state.exercise.resources.map((item)=>item.id);
  const activeInjectIds=activeInjects(state.exercise).map((item)=>item.id);
  const responseOpen=isResponseOpen();
  const cursorSchema={type:'integer',description:'Character cursor returned by the previous segment.',minimum:0,maximum:1000000};
  const tools=[
    {name:'drillboard_read_room',title:'Read exercise room',description:'Read a compact room summary, or a bounded JSON section. For sections, continue with nextCursor until null.',inputSchema:objectSchema({section:stringSchema('Room section.',{enum:roomSections}),cursor:cursorSchema}),annotations:readOnly,execute:async({section='summary',cursor=0})=>roomSummary(section,cursor)},
    {name:'drillboard_list_open_risks',title:'List open risks',description:'Read bounded JSON segments of open inject, objective, response, or communication risks. Continue with nextCursor until null.',inputSchema:objectSchema({kind:stringSchema('Risk group.',{enum:['all','injects','objectives','responses','communications']}),cursor:cursorSchema}),annotations:readOnly,execute:async({kind='all',cursor=0})=>riskPage(kind,cursor)},
    {name:'drillboard_export_after_action',title:'Export after-action record',description:'Read a bounded Markdown AAR section without changing phase or closing. Continue with nextCursor until null; use full for the complete record.',inputSchema:objectSchema({section:stringSchema('AAR section.',{enum:aarSections}),cursor:cursorSchema}),annotations:readOnly,execute:async({section='summary',cursor=0})=>aarPage(section,cursor)},
    {name:'drillboard_focus_view',title:'Focus board view',description:'Bring one visible command-board section into the human viewport without changing exercise data.',inputSchema:objectSchema({view:stringSchema('Visible board section.',{enum:['situation','injects','responses','communications','forecast','risks','closeout']})},['view']),annotations:readOnly,execute:async({view})=>{document.querySelector(`[data-view="${view}"]`)?.scrollIntoView({behavior:'smooth',block:'start'});return {message:`Focused the ${view} board section.`,focused:view};}},
  ];
  if(!responseOpen)return tools;

  tools.push(
    {name:'drillboard_run_forecast',title:'Run seeded forecast',description:'Run a reproducible scenario stress test and publish its P10, median, and P90 ranges to the visible board.',inputSchema:objectSchema({horizon_minutes:{type:'integer',description:'Simulated minutes ahead.',minimum:15,maximum:240},simulations:{type:'integer',description:'Seeded paths to run.',minimum:100,maximum:3000},seed:{type:'integer',description:'Seed for reproducible output.',minimum:1,maximum:999999}}),annotations:mutation,execute:async({horizon_minutes=60,simulations=800,seed=42})=>{const forecast=forecastExercise(state.exercise,{horizonMinutes:horizon_minutes,simulations,seed});mutate(`Ran ${simulations}-path forecast`,'agent',(draft)=>{draft.exercise.forecasts=[...draft.exercise.forecasts.slice(-(COLLECTION_LIMITS.forecasts-1)),forecast];});return {message:`Published deterministic forecast ${forecast.runKey}.`,runKey:forecast.runKey,stateFingerprint:forecast.stateFingerprint,currentStateFingerprint:forecast.stateFingerprint,generatedAtClock:forecast.generatedAtClock,horizonMinutes:forecast.horizonMinutes,simulations:forecast.simulations,seed:forecast.seed,containmentProbability:forecast.containmentProbability,ranges:forecast.ranges,riskDrivers:forecast.riskDrivers,stale:false};}},
    {name:'drillboard_stage_response',title:'Stage response proposal',description:'Stage a bounded simulated response for visible user review. The WebMCP surface cannot approve or finalize it.',inputSchema:objectSchema({title:stringSchema('Short response title.',{minLength:3,maxLength:100}),category:stringSchema('Response category.',{enum:['containment','investigation','continuity','customer','safety','coordination']}),rationale:stringSchema('Evidence-based rationale.',{minLength:12,maxLength:700}),objective_id:stringSchema('Optional current objective ID.',{enum:objectiveIds}),resource_id:stringSchema('Optional current resource ID.',{enum:resourceIds}),resource_units:{type:'integer',description:'Resource units requested.',minimum:0,maximum:12},effects:effectSchema},['title','category','rationale','effects']),annotations:mutation,execute:async(input)=>{const result=stageProposal(state.exercise,input);setExerciseFromTool(result.exercise,`Staged response: ${result.proposal.title}`);document.querySelector('[data-view="responses"]')?.scrollIntoView({behavior:'smooth'});const {id,title,category,status,stagedAt,targetObjectiveId,resourceId,resourceUnits,effects}=result.proposal;return {message:'Response staged; no effects have been applied.',proposal:{id,title,category,status,stagedAt,targetObjectiveId,resourceId,resourceUnits,effects},userReviewRequired:true};}},
    {name:'drillboard_stage_communication',title:'Stage communication',description:'Draft a factual simulated stakeholder update for visible user review. This tool does not publish it.',inputSchema:objectSchema({audience:stringSchema('Intended audience.',{enum:['customers','employees','executives','partners','public','responders']}),purpose:stringSchema('Purpose of the update.',{minLength:3,maxLength:100}),message:stringSchema('Factual draft without invented claims.',{minLength:12,maxLength:900})},['audience','purpose','message']),annotations:mutation,execute:async(input)=>{const result=stageCommunication(state.exercise,input);setExerciseFromTool(result.exercise,`Staged communication to ${result.communication.audience}`);const {id,audience,purpose,status,stagedAt}=result.communication;return {message:'Communication staged; it has not been published.',communication:{id,audience,purpose,status,stagedAt},userReviewRequired:true};}},
    {name:'drillboard_add_observation',title:'Add observation',description:'Add one factual scenario observation to the visible shared activity trail and after-action record.',inputSchema:objectSchema({observation:stringSchema('Observation grounded in board state.',{minLength:4,maxLength:500}),tags:{type:'array',items:stringSchema('Short tag.',{maxLength:30}),maxItems:8}},['observation']),annotations:mutation,execute:async(input)=>{const result=addObservation(state.exercise,input);setExerciseFromTool(result.exercise,`Observation: ${result.observation.text}`);return {message:'Observation added to the shared trail.',observation:{id:result.observation.id,tagCount:result.observation.tags.length,at:result.observation.at}};}},
    {name:'drillboard_stage_closeout',title:'Stage closeout',description:'Stage rationale and lessons for the visible user gate. The WebMCP surface cannot enter review or close.',inputSchema:objectSchema({rationale:stringSchema('Readiness rationale including unresolved items.',{minLength:20,maxLength:900}),lessons:{type:'array',description:'Candidate lessons learned.',items:stringSchema('One concise lesson.',{minLength:4,maxLength:240}),minItems:1,maxItems:8}},['rationale','lessons']),annotations:mutation,execute:async({rationale,lessons})=>{mutate('Staged exercise closeout','agent',(draft)=>{draft.exercise.closeout={...draft.exercise.closeout,staged:true,rationale,lessons};});document.querySelector('[data-view="closeout"]')?.scrollIntoView({behavior:'smooth'});return {message:'Closeout staged; the exercise remains in response.',staged:true,readiness:closeoutReadiness(state.exercise),userActionRequired:'Review staged items, then use the visible Enter closeout review control.'};}},
  );
  if(state.exercise.role==='facilitator'){
    tools.push(
      {name:'drillboard_create_inject',title:'Create scenario inject',description:'Create a bounded fictional exercise development. Available only in human-selected Facilitator mode.',inputSchema:objectSchema({title:stringSchema('Inject title.',{minLength:3,maxLength:100}),description:stringSchema('Observable fictional development.',{minLength:12,maxLength:700}),category:stringSchema('Inject category.',{enum:['technical','security','operations','safety','reputation','coordination','vendor']}),severity:{type:'integer',description:'Severity from 1 to 5.',minimum:1,maximum:5},delay_minutes:{type:'integer',description:'Minutes until activation.',minimum:0,maximum:180},deadline_minutes:{type:'integer',description:'Response window after activation.',minimum:5,maximum:240},effects:effectSchema},['title','description','category','severity','effects']),annotations:mutation,execute:async(input)=>{requireFacilitatorTool();const result=createInject(state.exercise,input);setExerciseFromTool(result.exercise,`Facilitator created inject: ${result.inject.title}`);const {id,title,category,severity,createdAt,deadline,status,effects}=result.inject;return {message:`Inject ${id} created for the simulation.`,inject:{id,title,category,severity,createdAt,deadline,status,effects}};}},
      {name:'drillboard_advance_clock',title:'Advance exercise clock',description:'Advance simulated time and apply exposure-weighted inject pressure. Facilitator mode only.',inputSchema:objectSchema({minutes:{type:'integer',description:'Minutes to advance.',minimum:5,maximum:120}},['minutes']),annotations:mutation,execute:async({minutes})=>{requireFacilitatorTool();const result=advanceExercise(state.exercise,minutes);setExerciseFromTool(result.exercise,`Facilitator advanced time by ${minutes} minutes`);return {message:`Advanced the exercise by ${minutes} minutes.`,clock:result.exercise.clock,activated:result.activated,overdueObjectives:[...new Set(result.overdue)],metrics:result.exercise.metrics};}},
      {name:'drillboard_update_objective',title:'Update objective',description:'Record bounded progress or status against a current exercise objective. Facilitator mode only.',inputSchema:objectSchema({objective_id:stringSchema('Current objective ID.',{enum:objectiveIds}),progress_delta:numberSchema('Progress change.',-100,100),status:stringSchema('Optional new status.',{enum:['open','blocked','complete']}),note:stringSchema('Short evidence note.',{maxLength:400})},['objective_id','progress_delta']),annotations:mutation,execute:async({objective_id,progress_delta,status,note=''})=>{requireFacilitatorTool();const result=updateObjective(state.exercise,objective_id,progress_delta,status,note);setExerciseFromTool(result.exercise,`Facilitator updated objective: ${result.objective.title}`);const {id,title,progress,status:objectiveStatus,updatedAt}=result.objective;return {message:`Objective ${objective_id} updated.`,objective:{id,title,progress,status:objectiveStatus,updatedAt}};}},
    );
    if(activeInjectIds.length)tools.push({name:'drillboard_resolve_inject',title:'Resolve active inject',description:'Record the observed fictional outcome of a currently active inject. Facilitator mode only.',inputSchema:objectSchema({inject_id:stringSchema('Currently active inject ID.',{enum:activeInjectIds}),outcome:stringSchema('Observed simulated outcome.',{minLength:5,maxLength:500})},['inject_id','outcome']),annotations:mutation,execute:async({inject_id,outcome})=>{requireFacilitatorTool();const result=resolveInject(state.exercise,inject_id,outcome);setExerciseFromTool(result.exercise,`Facilitator resolved inject: ${result.inject.title}`);return {message:`Inject ${inject_id} resolved.`,inject:{id:result.inject.id,title:result.inject.title,status:result.inject.status,resolvedAt:result.inject.resolvedAt}};}});
  }
  return tools;
}
async function syncTools(){await registry.sync(definitions());renderToolLab();}

for(const [key,preset] of Object.entries(PRESETS)){const option=document.createElement('option');option.value=key;option.textContent=preset.name;elements.preset.append(option);}
elements.preset.addEventListener('change',()=>resetExercise(elements.preset.value));
elements.role.addEventListener('change',()=>mutate(`Changed agent role to ${elements.role.value}`,'human',(draft)=>{draft.exercise.role=elements.role.value;}));
elements.reset.addEventListener('click',()=>resetExercise());
elements.undo.addEventListener('click',undo);
elements.advance15.addEventListener('click',()=>{const result=advanceExercise(state.exercise,15);replaceExercise(result.exercise,'Human advanced time by 15 minutes','human');});
elements.advance30.addEventListener('click',()=>{const result=advanceExercise(state.exercise,30);replaceExercise(result.exercise,'Human advanced time by 30 minutes','human');});
elements.forecastButton.addEventListener('click',()=>{const forecast=forecastExercise(state.exercise,{horizonMinutes:60,simulations:800,seed:42});mutate('Human ran 800-path forecast','human',(draft)=>{draft.exercise.forecasts=[...draft.exercise.forecasts.slice(-(COLLECTION_LIMITS.forecasts-1)),forecast];});});
elements.exportButton.addEventListener('click',()=>downloadText('drillboard-after-action.md',exportAfterAction(state.exercise,state.activity)));
function syncCloseoutDraft(){const lessons=elements.closeoutLessons.value.split('\n').map((line)=>line.trim()).filter(Boolean);if(lessons.length>8)throw new Error('Record at most 8 closeout lessons.');state=commitState(state,(draft)=>{draft.exercise.closeout.rationale=elements.closeoutRationale.value;draft.exercise.closeout.lessons=lessons;draft.history=[];},persist);}
function saveCloseoutInput(){try{syncCloseoutDraft();renderCloseout();}catch(error){renderCloseout();elements.closeoutStatus.textContent=error instanceof Error?error.message:String(error);}}
elements.closeoutRationale.addEventListener('input',saveCloseoutInput);
elements.closeoutLessons.addEventListener('input',saveCloseoutInput);
elements.closeoutReviewButton.addEventListener('click',()=>{try{syncCloseoutDraft();const result=enterCloseoutReview(state.exercise);state=commitState(state,(draft)=>{draft.exercise=result.exercise;draft.activity=[{time:nowLabel(),actor:'human',label:'Human entered closeout review; mutation tools removed'},...draft.activity].slice(0,60);},persist);render();}catch(error){elements.closeoutStatus.textContent=error instanceof Error?error.message:String(error);}});
elements.resumeResponseButton.addEventListener('click',()=>{try{const result=resumeResponse(state.exercise);state=commitState(state,(draft)=>{draft.exercise=result.exercise;draft.activity=[{time:nowLabel(),actor:'human',label:'Human resumed the response phase'},...draft.activity].slice(0,60);},persist);render();}catch(error){elements.closeoutStatus.textContent=error instanceof Error?error.message:String(error);}});
elements.closeoutButton.addEventListener('click',()=>{if(!elements.closeoutCheck.checked){elements.closeoutStatus.textContent='Check the human confirmation before closing the exercise.';return;}try{syncCloseoutDraft();const result=closeExercise(state.exercise,new Date().toISOString());state=commitState(state,(draft)=>{draft.exercise=result.exercise;draft.history=[];draft.activity=[{time:nowLabel(),actor:'human',label:'Human closed the tabletop exercise'},...draft.activity].slice(0,60);},persist);render();downloadText('drillboard-final-after-action.md',exportAfterAction(state.exercise,state.activity));}catch(error){elements.closeoutStatus.textContent=error instanceof Error?error.message:String(error);}});
elements.theme.addEventListener('click',()=>{state=commitState(state,(draft)=>{draft.theme=draft.theme==='dark'?'light':'dark';},persist);render();});
elements.toolButton.addEventListener('click',()=>{renderToolLab();elements.toolDialog.showModal();});
elements.toolClose.addEventListener('click',()=>elements.toolDialog.close());
elements.toolSelect.addEventListener('change',()=>{const tool=registry.listTools().find((candidate)=>candidate.name===elements.toolSelect.value);elements.toolInput.value=JSON.stringify(schemaExample(tool?.inputSchema),null,2);});
elements.toolRun.addEventListener('click',async()=>{try{const input=JSON.parse(elements.toolInput.value||'{}');const result=await registry.executeTool(elements.toolSelect.value,input);elements.toolOutput.textContent=JSON.stringify(result,null,2);}catch(error){elements.toolOutput.textContent=`Error: ${error instanceof Error?error.message:String(error)}`;}});
window.addEventListener('beforeunload',persist);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
