import { PRESETS } from './data.js';
import { activeInjects, advanceExercise, createExercise, createInject, decideCommunication, decideProposal, exerciseScore, exportAfterAction, forecastExercise, formatClock, metricTone, openRisks, resolveInject, stageCommunication, stageProposal, updateObjective } from './engine.js';
import { createWebMCPRegistry, toolResult } from './webmcp.js';

const STORAGE_KEY = 'drillboard.exercise.v1';
const MAX_HISTORY = 36;
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const elements = {
  preset: $('#preset-select'), role: $('#role-select'), reset: $('#reset-exercise'), advance15: $('#advance-15'), advance30: $('#advance-30'), undo: $('#undo-change'),
  clock: $('#exercise-clock'), scenarioTitle: $('#scenario-title'), scenarioSubtitle: $('#scenario-subtitle'), status: $('#exercise-status'), score: $('#exercise-score'),
  impact: $('#metric-impact'), uncertainty: $('#metric-uncertainty'), fatigue: $('#metric-fatigue'), trust: $('#metric-trust'), service: $('#metric-service'),
  objectives: $('#objective-list'), injects: $('#inject-list'), resources: $('#resource-list'), proposals: $('#proposal-list'), communications: $('#communication-list'),
  forecast: $('#forecast-panel'), riskList: $('#risk-list'), activity: $('#activity-list'), webmcpStatus: $('#webmcp-status'), toolButton: $('#tool-lab-button'),
  toolDialog: $('#tool-dialog'), toolSelect: $('#tool-select'), toolInput: $('#tool-input'), toolRun: $('#tool-run'), toolOutput: $('#tool-output'), toolClose: $('#close-tool-dialog'),
  forecastButton: $('#run-forecast'), exportButton: $('#export-aar'), closeoutRationale: $('#closeout-rationale'), closeoutLessons: $('#closeout-lessons'),
  closeoutCheck: $('#closeout-check'), closeoutButton: $('#closeout-button'), closeoutStatus: $('#closeout-status'), theme: $('#theme-toggle'), roleCopy: $('#role-copy'),
};

function nowLabel() { return new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date()); }
function initialState(preset='outage') { return { exercise:createExercise(preset), history:[], activity:[{time:nowLabel(),actor:'human',label:`Opened ${PRESETS[preset].name}`}], theme:'dark' }; }
function loadState(){ try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)); if(parsed?.exercise?.version===1) return parsed;}catch{} return initialState(); }
let state=loadState();
function persist(){ localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); }
function snapshot(){ return JSON.stringify({exercise:state.exercise,activity:state.activity}); }
function mutate(label,actor,operation,{history=true}={}){
  if(state.exercise.status==='closed') throw new Error('The exercise is closed and read-only. Reset it to start another drill.');
  if(history) state.history=[...state.history.slice(-(MAX_HISTORY-1)),snapshot()];
  operation(); state.activity=[{time:nowLabel(),actor,label},...state.activity].slice(0,60); persist(); render();
}
function undo(){const previous=state.history.pop(); if(!previous)return; const restored=JSON.parse(previous); const history=state.history; state={...state,...restored,history}; state.activity=[{time:nowLabel(),actor:'human',label:'Undid the previous simulation change'},...state.activity].slice(0,60);persist();render();}
function resetExercise(key=state.exercise.presetKey){ state=initialState(key);persist();render(); }
function replaceExercise(next,label,actor){ mutate(label,actor,()=>{state.exercise=next;state.exercise.closeout.staged=false;}); }
function escapeHtml(value){return String(value).replace(/[&<>\"]/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'})[character]);}
function downloadText(filename,content){const blob=new Blob([content],{type:'text/markdown'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}

function renderHeader(){
  elements.preset.value=state.exercise.presetKey; elements.role.value=state.exercise.role; elements.clock.textContent=formatClock(state.exercise.clock);
  elements.scenarioTitle.textContent=state.exercise.title; elements.scenarioSubtitle.textContent=state.exercise.subtitle; elements.status.textContent=state.exercise.status;
  elements.score.textContent=exerciseScore(state.exercise); elements.undo.disabled=!state.history.length; elements.advance15.disabled=elements.advance30.disabled=state.exercise.status==='closed';
  elements.roleCopy.textContent=state.exercise.role==='coach'
    ? 'Coach mode: the agent can analyze and stage responses, but cannot create injects or advance exercise time.'
    : 'Facilitator mode: the agent may create injects, advance time, and update scenario state. Human response approval still remains visible-only.';
}
function renderMetric(key,element){const value=Math.round(state.exercise.metrics[key]);element.querySelector('strong').textContent=value;element.querySelector('.meter-fill').style.width=`${value}%`;element.dataset.tone=metricTone(key,value);}
function renderMetrics(){for(const [key,element] of Object.entries({impact:elements.impact,uncertainty:elements.uncertainty,fatigue:elements.fatigue,trust:elements.trust,service:elements.service}))renderMetric(key,element);}
function renderObjectives(){elements.objectives.innerHTML=state.exercise.objectives.map((objective)=>`<li class="objective ${objective.status}"><div><span class="priority ${objective.priority}">${objective.priority}</span><strong>${escapeHtml(objective.title)}</strong><small>${escapeHtml(objective.owner)} · deadline T+${formatClock(objective.deadline)}</small></div><div class="progress-wrap"><span>${Math.round(objective.progress)}%</span><div class="progress"><i style="width:${objective.progress}%"></i></div></div>${objective.status!=='complete'&&state.exercise.status==='open'?`<button class="mini-button" data-progress-objective="${objective.id}">+20%</button>`:''}</li>`).join('');
  $$('[data-progress-objective]').forEach((button)=>button.addEventListener('click',()=>{const result=updateObjective(state.exercise,button.dataset.progressObjective,20,null,'Human exercise update');replaceExercise(result.exercise,`Advanced objective: ${result.objective.title}`,'human');}));}
function renderInjects(){const sorted=[...state.exercise.injects].sort((a,b)=>b.createdAt-a.createdAt);elements.injects.innerHTML=sorted.map((inject)=>`<li class="inject ${inject.status} ${inject.createdAt>state.exercise.clock?'future':''}"><div class="inject-time">T+${formatClock(inject.createdAt)}</div><div><span class="category">${escapeHtml(inject.category)}</span><strong>${escapeHtml(inject.title)}</strong><p>${escapeHtml(inject.description)}</p><small>Severity ${inject.severity} · deadline T+${formatClock(inject.deadline)} · ${inject.status}</small>${inject.outcome?`<em>${escapeHtml(inject.outcome)}</em>`:''}</div>${inject.status==='active'&&inject.createdAt<=state.exercise.clock&&state.exercise.status==='open'?`<button class="mini-button" data-resolve-inject="${inject.id}">Resolve</button>`:''}</li>`).join('');
  $$('[data-resolve-inject]').forEach((button)=>button.addEventListener('click',()=>{const outcome=prompt('Record the simulated outcome:','Contained through the approved response.');if(!outcome)return;const result=resolveInject(state.exercise,button.dataset.resolveInject,outcome);replaceExercise(result.exercise,`Resolved inject: ${result.inject.title}`,'human');}));}
function renderResources(){elements.resources.innerHTML=state.exercise.resources.map((resource)=>{const available=resource.total-resource.allocated;return `<li><div><strong>${escapeHtml(resource.name)}</strong><small>${available} available · ${resource.allocated} allocated</small></div><div class="resource-dots" aria-label="${resource.allocated} of ${resource.total} allocated">${Array.from({length:resource.total},(_,index)=>`<i class="${index<resource.allocated?'used':''}"></i>`).join('')}</div></li>`;}).join('');}
function renderProposals(){const proposals=[...state.exercise.proposals].reverse();elements.proposals.innerHTML=proposals.length?proposals.map((proposal)=>`<article class="proposal ${proposal.status}"><div class="proposal-heading"><span class="category">${escapeHtml(proposal.category)}</span><strong>${escapeHtml(proposal.title)}</strong><span class="proposal-status">${proposal.status}</span></div><p>${escapeHtml(proposal.rationale)}</p><div class="effect-row">${Object.entries(proposal.effects).filter(([,value])=>value).map(([key,value])=>`<span>${key} ${value>0?'+':''}${value}</span>`).join('')||'<span>No direct metric effect</span>'}${proposal.resourceId?`<span>${proposal.resourceUnits} × ${escapeHtml(proposal.resourceId)}</span>`:''}</div>${proposal.status==='staged'&&state.exercise.status==='open'?`<div class="button-row"><button class="button ghost" data-reject-proposal="${proposal.id}">Reject</button><button class="button primary" data-approve-proposal="${proposal.id}">Approve response</button></div>`:''}</article>`).join(''):'<p class="empty">Agent-staged responses will appear here for human review.</p>';
  $$('[data-approve-proposal]').forEach((button)=>button.addEventListener('click',()=>{const note=prompt('Optional human decision note:','Approved for the simulation.');const result=decideProposal(state.exercise,button.dataset.approveProposal,'approved',note||'');replaceExercise(result.exercise,`Human approved response: ${result.proposal.title}`,'human');}));
  $$('[data-reject-proposal]').forEach((button)=>button.addEventListener('click',()=>{const result=decideProposal(state.exercise,button.dataset.rejectProposal,'rejected','Rejected during human review.');replaceExercise(result.exercise,`Human rejected response: ${result.proposal.title}`,'human');}));}
function renderCommunications(){const items=[...state.exercise.communications].reverse();elements.communications.innerHTML=items.length?items.map((item)=>`<li class="communication ${item.status}"><div><span class="category">${escapeHtml(item.audience)}</span><strong>${escapeHtml(item.purpose)}</strong><p>${escapeHtml(item.message)}</p></div>${item.status==='staged'&&state.exercise.status==='open'?`<div class="button-row"><button class="mini-button" data-reject-comms="${item.id}">Reject</button><button class="mini-button approve" data-approve-comms="${item.id}">Approve</button></div>`:`<span>${item.status}</span>`}</li>`).join(''):'<li class="empty">No communication drafts are staged.</li>';
  $$('[data-approve-comms]').forEach((button)=>button.addEventListener('click',()=>{const result=decideCommunication(state.exercise,button.dataset.approveComms,'approved');replaceExercise(result.exercise,`Human approved communication to ${result.communication.audience}`,'human');}));
  $$('[data-reject-comms]').forEach((button)=>button.addEventListener('click',()=>{const result=decideCommunication(state.exercise,button.dataset.rejectComms,'rejected');replaceExercise(result.exercise,`Human rejected communication to ${result.communication.audience}`,'human');}));}
function renderForecast(){const forecast=state.exercise.forecasts.at(-1);if(!forecast){elements.forecast.innerHTML='<p class="empty">Run a seeded forecast to stress-test the current response posture.</p>';return;}elements.forecast.innerHTML=`<div class="forecast-score"><strong>${forecast.containmentProbability}%</strong><span>containment probability in ${forecast.horizonMinutes} minutes</span></div><div class="forecast-ranges"><span>Impact median <b>${forecast.ranges.impact.median}</b></span><span>Service median <b>${forecast.ranges.service.median}</b></span><span>Exercise score median <b>${forecast.ranges.score.median}</b></span></div><div><h3>Risk drivers</h3><ul>${forecast.riskDrivers.length?forecast.riskDrivers.map((driver)=>`<li>${escapeHtml(driver)}</li>`).join(''):'<li>No dominant driver identified.</li>'}</ul></div>`;}
function renderRisks(){const risks=openRisks(state.exercise);const items=[...risks.activeInjects.map((risk)=>({label:risk.title,meta:`inject · severity ${risk.severity}`,overdue:risk.overdue})),...risks.openObjectives.map((risk)=>({label:risk.title,meta:`objective · ${risk.progress}%`,overdue:risk.overdue})),...risks.stagedResponses.map((risk)=>({label:risk.title,meta:'awaiting human response review',overdue:false})),...risks.stagedCommunications.map((risk)=>({label:`${risk.audience}: ${risk.purpose}`,meta:'awaiting communication review',overdue:false}))];elements.riskList.innerHTML=items.length?items.map((item)=>`<li class="${item.overdue?'overdue':''}"><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(item.meta)}</small></li>`).join(''):'<li class="empty">No open risks.</li>';}
function renderActivity(){elements.activity.innerHTML=state.activity.map((item)=>`<li><span class="actor ${item.actor}">${item.actor}</span><span>${escapeHtml(item.label)}</span><time>${item.time}</time></li>`).join('');}
function renderCloseout(){elements.closeoutRationale.value=state.exercise.closeout.rationale||'';elements.closeoutLessons.value=(state.exercise.closeout.lessons||[]).join('\n');elements.closeoutCheck.checked=false;elements.closeoutCheck.disabled=state.exercise.status==='closed';elements.closeoutButton.disabled=state.exercise.status==='closed';elements.closeoutStatus.textContent=state.exercise.status==='closed'?`Exercise closed ${new Date(state.exercise.closeout.closedAt).toLocaleString()}. Mutation tools are disabled.`:state.exercise.closeout.staged?'Agent closeout is staged. A person must review and close the exercise.':'No closeout recommendation is staged.';elements.closeoutStatus.className=`closeout-status ${state.exercise.status==='closed'?'closed':state.exercise.closeout.staged?'staged':''}`;}
function renderToolLab(){const tools=registry.listTools();const current=elements.toolSelect.value;elements.toolSelect.innerHTML=tools.map((tool)=>`<option value="${tool.name}">${tool.name}</option>`).join('');if(tools.some((tool)=>tool.name===current))elements.toolSelect.value=current;elements.webmcpStatus.textContent=`${registry.status().mode==='native'?'Native WebMCP':'Tool Lab fallback'} · ${tools.length} tools`;elements.webmcpStatus.dataset.mode=registry.status().mode;}
function render(){document.documentElement.dataset.theme=state.theme;elements.theme.textContent=state.theme==='dark'?'Light':'Dark';renderHeader();renderMetrics();renderObjectives();renderInjects();renderResources();renderProposals();renderCommunications();renderForecast();renderRisks();renderActivity();renderCloseout();syncTools();}

const registry=createWebMCPRegistry({bridgeName:'__drillboardWebMCP',onStatus:renderToolLab});
const objectSchema=(properties={},required=[])=>({type:'object',properties,required,additionalProperties:false});
const stringSchema=(description,options={})=>({type:'string',description,...options});
const numberSchema=(description,minimum,maximum)=>({type:'number',description,minimum,maximum});
const effectSchema={type:'object',description:'Simulated metric deltas. Negative impact/uncertainty/fatigue and positive trust/service are beneficial.',properties:{impact:numberSchema('Impact delta.',-20,20),uncertainty:numberSchema('Uncertainty delta.',-20,20),fatigue:numberSchema('Fatigue delta.',-20,20),trust:numberSchema('Trust delta.',-20,20),service:numberSchema('Service-health delta.',-20,20)},additionalProperties:false};
const readOnly={readOnlyHint:true,idempotentHint:true,openWorldHint:false,untrustedContentHint:true};
const reversible={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false,untrustedContentHint:true};
function roomSummary(){return {scenario:{title:state.exercise.title,subtitle:state.exercise.subtitle,clock:state.exercise.clock,clockFormatted:formatClock(state.exercise.clock),status:state.exercise.status,agentRole:state.exercise.role},score:exerciseScore(state.exercise),metrics:state.exercise.metrics,resources:state.exercise.resources,objectives:state.exercise.objectives,activeInjects:activeInjects(state.exercise),stagedResponses:state.exercise.proposals.filter((item)=>item.status==='staged'),stagedCommunications:state.exercise.communications.filter((item)=>item.status==='staged'),latestForecast:state.exercise.forecasts.at(-1)||null,humanControlBoundary:'Agents may stage responses, communications, and closeout. Only visible human controls approve responses, publish communications, and close the exercise.'};}
function setExerciseFromTool(next,label){state.exercise=next;state.exercise.closeout.staged=false;state.activity=[{time:nowLabel(),actor:'agent',label},...state.activity].slice(0,60);persist();render();}
function definitions(){const tools=[
  {name:'drillboard_read_room',description:'Read the current tabletop scenario, clock, metrics, resources, objectives, active injects, staged items, and human-control boundary.',inputSchema:objectSchema(),annotations:readOnly,execute:async()=>toolResult(roomSummary(),'Drillboard room')},
  {name:'drillboard_list_open_risks',description:'List active injects, open objectives, and staged items awaiting human review.',inputSchema:objectSchema(),annotations:readOnly,execute:async()=>toolResult(openRisks(state.exercise),'Open exercise risks')},
  {name:'drillboard_export_after_action',description:'Return a Markdown after-action record without closing the exercise.',inputSchema:objectSchema(),annotations:readOnly,execute:async()=>toolResult({markdown:exportAfterAction(state.exercise,state.activity),status:state.exercise.status},'After-action record')},
  {name:'drillboard_focus_view',description:'Bring a command-board section into the human viewport.',inputSchema:objectSchema({view:stringSchema('Board section.',{enum:['situation','injects','responses','communications','forecast','risks','closeout']})},['view']),annotations:{...readOnly,idempotentHint:false},execute:async({view})=>{document.querySelector(`[data-view="${view}"]`)?.scrollIntoView({behavior:'smooth',block:'start'});return toolResult({focused:view},'Focused view');}},
];
if(state.exercise.status==='open'){
 tools.push(
  {name:'drillboard_run_forecast',description:'Run a deterministic Monte Carlo forecast and publish the result to the visible board.',inputSchema:objectSchema({horizon_minutes:{type:'integer',description:'Forecast horizon in simulated minutes.',minimum:15,maximum:240},simulations:{type:'integer',description:'Number of simulations.',minimum:100,maximum:3000},seed:{type:'integer',description:'Deterministic random seed.',minimum:1,maximum:999999}},[]),annotations:reversible,execute:async({horizon_minutes=60,simulations=800,seed=42})=>{const forecast=forecastExercise(state.exercise,{horizonMinutes:horizon_minutes,simulations,seed});mutate(`Ran ${simulations}-path forecast`,'agent',()=>{state.exercise.forecasts=[...state.exercise.forecasts.slice(-7),forecast];},{history:false});return toolResult(forecast,'Forecast complete');}},
  {name:'drillboard_stage_response',description:'Stage a simulated response for visible human approval. This tool cannot approve or execute the response as an official decision.',inputSchema:objectSchema({title:stringSchema('Short response title.',{minLength:3,maxLength:100}),category:stringSchema('Response category.',{enum:['containment','investigation','continuity','customer','safety','coordination']}),rationale:stringSchema('Why this response fits the current situation.',{minLength:12,maxLength:700}),objective_id:stringSchema('Optional objective ID this response advances.'),resource_id:stringSchema('Optional simulated resource ID.'),resource_units:{type:'integer',description:'Resource units requested.',minimum:0,maximum:12},effects:effectSchema},['title','category','rationale','effects']),annotations:reversible,execute:async(input)=>{const result=stageProposal(state.exercise,input);setExerciseFromTool(result.exercise,`Staged response: ${result.proposal.title}`);document.querySelector('[data-view="responses"]')?.scrollIntoView({behavior:'smooth'});return toolResult({...result.proposal,humanApprovalRequired:true},'Response staged') }},
  {name:'drillboard_stage_communication',description:'Draft a simulated stakeholder update for visible human approval. This tool does not publish the message.',inputSchema:objectSchema({audience:stringSchema('Intended audience.',{enum:['customers','employees','executives','partners','public','responders']}),purpose:stringSchema('Purpose of the update.',{minLength:3,maxLength:100}),message:stringSchema('Clear factual draft without invented claims.',{minLength:12,maxLength:900})},['audience','purpose','message']),annotations:reversible,execute:async(input)=>{const result=stageCommunication(state.exercise,input);setExerciseFromTool(result.exercise,`Staged communication to ${result.communication.audience}`);return toolResult({...result.communication,humanApprovalRequired:true},'Communication staged');}},
  {name:'drillboard_add_observation',description:'Add a factual training observation to the shared exercise log.',inputSchema:objectSchema({observation:stringSchema('Observation grounded in the visible scenario.',{minLength:4,maxLength:500}),tags:{type:'array',items:stringSchema('Short tag.',{maxLength:30}),maxItems:8}},['observation']),annotations:reversible,execute:async({observation,tags=[]})=>{mutate('Added agent observation','agent',()=>{state.exercise.observations.push({id:`observation-${state.exercise.sequence++}`,text:observation,tags,at:state.exercise.clock});});return toolResult({observation,tags,clock:state.exercise.clock},'Observation recorded');}},
  {name:'drillboard_stage_closeout',description:'Stage a closeout rationale and lessons for human review. There is deliberately no tool that closes the exercise.',inputSchema:objectSchema({rationale:stringSchema('Why the simulation is ready to close, including unresolved items.',{minLength:20,maxLength:900}),lessons:{type:'array',description:'Candidate lessons learned.',items:stringSchema('One concise lesson.',{minLength:4,maxLength:240}),minItems:1,maxItems:8}},['rationale','lessons']),annotations:reversible,execute:async({rationale,lessons})=>{mutate('Staged exercise closeout','agent',()=>{state.exercise.closeout={...state.exercise.closeout,staged:true,rationale,lessons};});document.querySelector('[data-view="closeout"]')?.scrollIntoView({behavior:'smooth'});return toolResult({staged:true,rationale,lessons,humanActionRequired:'Review the visible closeout gate and press Close exercise.'},'Closeout staged');}},
  {name:'drillboard_undo_last_change',description:'Undo the most recent reversible exercise mutation.',inputSchema:objectSchema(),annotations:reversible,execute:async()=>{if(!state.history.length)throw new Error('No change is available to undo.');undo();return toolResult(roomSummary(),'Last change undone');}}
 );
 if(state.exercise.role==='facilitator')tools.push(
  {name:'drillboard_create_inject',description:'Create a new simulated exercise inject. Available only while the human has selected facilitator mode.',inputSchema:objectSchema({title:stringSchema('Inject title.',{minLength:3,maxLength:100}),description:stringSchema('Observable scenario development, not hidden instructions.',{minLength:12,maxLength:700}),category:stringSchema('Inject category.',{enum:['technical','security','operations','safety','reputation','coordination','vendor']}),severity:{type:'integer',description:'Severity from 1 to 5.',minimum:1,maximum:5},delay_minutes:{type:'integer',description:'Minutes until the inject becomes active.',minimum:0,maximum:180},deadline_minutes:{type:'integer',description:'Minutes from now until the inject is overdue.',minimum:5,maximum:240},effects:effectSchema},['title','description','category','severity','effects']),annotations:reversible,execute:async(input)=>{const result=createInject(state.exercise,input);setExerciseFromTool(result.exercise,`Facilitator created inject: ${result.inject.title}`);return toolResult(result.inject,'Inject created');}},
  {name:'drillboard_advance_clock',description:'Advance simulated exercise time and apply active pressure. Available only in facilitator mode.',inputSchema:objectSchema({minutes:{type:'integer',description:'Minutes to advance.',minimum:5,maximum:120}},['minutes']),annotations:reversible,execute:async({minutes})=>{const result=advanceExercise(state.exercise,minutes);setExerciseFromTool(result.exercise,`Facilitator advanced time by ${minutes} minutes`);return toolResult({clock:result.exercise.clock,activated:result.activated,overdue:result.overdue,metrics:result.exercise.metrics},'Clock advanced');}},
  {name:'drillboard_update_objective',description:'Update progress or status for one exercise objective. Available only in facilitator mode.',inputSchema:objectSchema({objective_id:stringSchema('Objective ID.'),progress_delta:numberSchema('Progress change.',-100,100),status:stringSchema('Optional status.',{enum:['open','blocked','complete']}),note:stringSchema('Short evidence note.',{maxLength:400})},['objective_id','progress_delta']),annotations:reversible,execute:async({objective_id,progress_delta,status,note=''})=>{const result=updateObjective(state.exercise,objective_id,progress_delta,status,note);setExerciseFromTool(result.exercise,`Facilitator updated objective: ${result.objective.title}`);return toolResult(result.objective,'Objective updated');}},
  {name:'drillboard_resolve_inject',description:'Mark a simulated inject resolved and record its outcome. Available only in facilitator mode.',inputSchema:objectSchema({inject_id:stringSchema('Inject ID.'),outcome:stringSchema('Observed simulated outcome.',{minLength:5,maxLength:500})},['inject_id','outcome']),annotations:reversible,execute:async({inject_id,outcome})=>{const result=resolveInject(state.exercise,inject_id,outcome);setExerciseFromTool(result.exercise,`Facilitator resolved inject: ${result.inject.title}`);return toolResult(result.inject,'Inject resolved');}}
 );
}
return tools;}
async function syncTools(){await registry.sync(definitions());renderToolLab();}

for(const [key,preset] of Object.entries(PRESETS)){const option=document.createElement('option');option.value=key;option.textContent=preset.name;elements.preset.append(option);}
elements.preset.addEventListener('change',()=>resetExercise(elements.preset.value));
elements.role.addEventListener('change',()=>mutate(`Changed agent role to ${elements.role.value}`,'human',()=>{state.exercise.role=elements.role.value;}));
elements.reset.addEventListener('click',()=>resetExercise());
elements.undo.addEventListener('click',undo);
elements.advance15.addEventListener('click',()=>{const result=advanceExercise(state.exercise,15);replaceExercise(result.exercise,'Human advanced time by 15 minutes','human');});
elements.advance30.addEventListener('click',()=>{const result=advanceExercise(state.exercise,30);replaceExercise(result.exercise,'Human advanced time by 30 minutes','human');});
elements.forecastButton.addEventListener('click',()=>{const forecast=forecastExercise(state.exercise,{horizonMinutes:60,simulations:800,seed:42});mutate('Human ran 800-path forecast','human',()=>{state.exercise.forecasts=[...state.exercise.forecasts.slice(-7),forecast];},{history:false});});
elements.exportButton.addEventListener('click',()=>downloadText('drillboard-after-action.md',exportAfterAction(state.exercise,state.activity)));
elements.closeoutRationale.addEventListener('input',()=>{state.exercise.closeout.rationale=elements.closeoutRationale.value;persist();});
elements.closeoutLessons.addEventListener('input',()=>{state.exercise.closeout.lessons=elements.closeoutLessons.value.split('\n').map((line)=>line.trim()).filter(Boolean);persist();});
elements.closeoutButton.addEventListener('click',()=>{if(!elements.closeoutCheck.checked){elements.closeoutStatus.textContent='Check the human confirmation before closing the exercise.';return;}state.exercise.closeout={...state.exercise.closeout,rationale:elements.closeoutRationale.value,lessons:elements.closeoutLessons.value.split('\n').map((line)=>line.trim()).filter(Boolean),closedAt:new Date().toISOString()};state.exercise.status='closed';state.activity=[{time:nowLabel(),actor:'human',label:'Human closed the tabletop exercise'},...state.activity].slice(0,60);persist();render();downloadText('drillboard-final-after-action.md',exportAfterAction(state.exercise,state.activity));});
elements.theme.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';persist();render();});
elements.toolButton.addEventListener('click',()=>{renderToolLab();elements.toolDialog.showModal();});
elements.toolClose.addEventListener('click',()=>elements.toolDialog.close());
elements.toolSelect.addEventListener('change',()=>{const tool=registry.listTools().find((candidate)=>candidate.name===elements.toolSelect.value);const example={};for(const required of tool?.inputSchema?.required??[]){const schema=tool.inputSchema.properties[required];if(schema.type==='object')example[required]={};else if(schema.type==='array')example[required]=[];else example[required]=schema.enum?.[0]??(schema.type==='integer'||schema.type==='number'?schema.minimum??1:schema.type==='boolean'?true:'');}elements.toolInput.value=JSON.stringify(example,null,2);});
elements.toolRun.addEventListener('click',async()=>{try{const input=JSON.parse(elements.toolInput.value||'{}');const result=await registry.executeTool(elements.toolSelect.value,input);elements.toolOutput.textContent=JSON.stringify(result,null,2);}catch(error){elements.toolOutput.textContent=`Error: ${error instanceof Error?error.message:String(error)}`;}});
window.addEventListener('beforeunload',persist);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
